name: Build and test panna porom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
    - name: code irukkanu check pannu
      uses: actions/checkout@v4
    
    - name: Java install pannu
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven' 
    - name: Dai Java irukkiya??
      run: |
          echo "Hha Hha Irukka enna ippo"
          java --version
          
    - name: maven test pannaporen 
      run: |
         cd MyWebApp/
         mvn test

    - name: maven build panna poren
      run: |
       cd MyWebApp/
       mvn clean package
      
